export const options = [
    {
        label: 'Kamień',
        options: [
            { value: 153, label: 'Kamień' },
            { value: 155, label: 'Kamień Cegielnia' },
            { value: 151, label: 'R-k Kamień Las' },
            { value: 162, label: 'R-k Kamień Pojdy' },
            { value: 152, label: 'R-k Kamień Robotnicza' },
            { value: 156, label: 'R-k Kamień Rzędówka' },
            { value: 163, label: 'R-k Kamień Skrzyżowanie' },
            { value: 251, label: 'R-k Kamień Szewczyka' },
            { value: 154, label: 'R-k Kamień Szkoła' },
        ],
    },
    {
        label: 'Adamowice',
        options: [
            { value: 325, label: 'Adamowice Centrum' },
            { value: 326, label: 'Adamowice Las' },
        ],
    },
    {
        label: 'Biertułtowy',
        options: [{ value: 230, label: 'Biertułtowy Mariacka' }],
    },
    {
        label: 'Bogunice',
        options: [
            { value: 328, label: 'Bogunice Bęczkowiec' },
            { value: 327, label: 'Bogunice Centrum' },
        ],
    },
    {
        label: 'Boguszowicka',
        options: [{ value: 365, label: 'Boguszowicka Cmentarz' }],
    },
    { label: 'Meksyk-Nowiny', options: [{ value: 336, label: 'Brzezińska' }] },
    {
        label: 'Buzowice',
        options: [{ value: 204, label: 'Buzowice Skrzyżowanie' }],
    },
    {
        label: 'Chwałęcice',
        options: [
            { value: 245, label: 'Chwałęcice  Przedszkole' },
            { value: 246, label: 'Chwałęcice  Szkoła' },
            { value: 143, label: 'R-k Chwałęcice  Goj' },
            { value: 109, label: 'R-k Chwałęcice  Kierchówek' },
            { value: 142, label: 'R-k Chwałęcice  Kościół' },
            { value: 407, label: 'R-k Chwałęcice  Kościół 1' },
            { value: 260, label: 'R-k Chwałęcice  Pniowiec' },
            { value: 108, label: 'R-k Chwałęcice  Przystań' },
            { value: 110, label: 'R-k Chwałęcice  Skrzyżowanie' },
        ],
    },
    {
        label: 'Chwałowice',
        options: [
            { value: 254, label: 'Chwałowice Skrzyżowanie' },
            { value: 224, label: 'R-k Chwałowice Kolonia' },
            { value: 65, label: 'R-k Chwałowice Kopalnia' },
            { value: 226, label: 'R-k Chwałowice Kożdoniów' },
            { value: 223, label: 'R-k Chwałowice Królewiok' },
            { value: 255, label: 'R-k Chwałowice Kupiecka' },
            { value: 103, label: 'R-k Chwałowice Las' },
            { value: 225, label: 'R-k Chwałowice Malchera' },
            { value: 66, label: 'R-k Chwałowice Osiedle' },
            { value: 67, label: 'R-k Chwałowice Pętla' },
            { value: 417, label: 'R-k Chwałowice Śląska' },
        ],
    },
    {
        label: 'Czernica',
        options: [
            { value: 302, label: 'Czernica Ośrodek Zdrowia' },
            { value: 184, label: 'Czernica przy Krzyżu' },
            { value: 183, label: 'Czernica Straż' },
        ],
    },
    { label: 'Dzimierz', options: [{ value: 320, label: 'Dzimierz' }] },
    {
        label: 'Gaszowice',
        options: [
            { value: 180, label: 'Gaszowice Cegielnia' },
            { value: 314, label: 'Gaszowice Las' },
            { value: 188, label: 'Gaszowice Pogwizdów' },
            { value: 192, label: 'Gaszowice Rydułtowska' },
            { value: 179, label: 'Gaszowice UG' },
        ],
    },
    {
        label: 'Gotartowice',
        options: [
            { value: 292, label: 'Gotartowice Pętla' },
            { value: 415, label: 'Gotartowice tymczasowy' },
            { value: 366, label: 'Gotartowicka Cmentarz' },
            { value: 27, label: 'R-k Gotartowice' },
            { value: 301, label: 'R-k Gotartowice Gotartowicka' },
            { value: 28, label: 'R-k Gotartowice Lotnisko' },
            { value: 44, label: 'R-k Gotartowice Straż' },
            { value: 170, label: 'R-k Gotartowice Sygnaąy' },
        ],
    },
    {
        label: 'Górki',
        options: [
            { value: 265, label: 'Górki Kościół' },
            { value: 266, label: 'Górki Remiza' },
        ],
    },
    {
        label: 'Jankowice',
        options: [
            { value: 273, label: 'Jankowice G.S.' },
            { value: 197, label: 'Jankowice Gwarek' },
            { value: 269, label: 'Jankowice Kościelna' },
            { value: 270, label: 'Jankowice Kościół' },
            { value: 227, label: 'Jankowice Pętla' },
            { value: 267, label: 'Jankowice Remiza' },
            { value: 272, label: 'Jankowice Rybnicka' },
            { value: 268, label: 'Jankowice Sklep' },
            { value: 274, label: 'Jankowice Skrzyżowanie' },
            { value: 198, label: 'Jankowice Świerklańska' },
            { value: 196, label: 'Jankowice Urząd Gminy' },
            { value: 271, label: 'Jankowice Wowry' },
        ],
    },
    {
        label: 'Jastrzębie',
        options: [
            { value: 392, label: 'Jastrzębie Al. Piłsudskiego-Os.Staszica' },
            { value: 385, label: 'Jastrzębie Al.Piłsudskiego-Os.Gwarków' },
            { value: 386, label: 'Jastrzębie Dworzec Arki Bołka' },
            { value: 395, label: 'Jastrzębie Dworzec Zdrój' },
            { value: 394, label: 'Jastrzębie Hala Sportowa' },
            { value: 389, label: 'Jastrzębie KWK Borynia' },
            { value: 391, label: 'Jastrzębie KWK Zofiówka' },
            { value: 396, label: 'Jastrzębie Szerocka Kaplica' },
            { value: 390, label: 'Jastrzębie Szerocka Os.1000-lecia' },
            { value: 393, label: 'Jastrzębie Szpital Wojewódzki' },
            { value: 387, label: 'Jastrzębie Urząd Skarbowy' },
            { value: 383, label: 'Jastrzębie Wodzisławska' },
            { value: 384, label: 'Jastrzębie Zdrojowa' },
        ],
    },
    {
        label: 'Jejkowice',
        options: [
            { value: 175, label: 'Jejkowice Centrum' },
            { value: 176, label: 'Jejkowice Kuźnia' },
            { value: 312, label: 'Jejkowice Sumińska' },
        ],
    },
    {
        label: 'Kłokocin',
        options: [
            { value: 315, label: 'Kłokocin Wiadukt' },
            { value: 139, label: 'R-k Kłokocin Osiedle' },
            { value: 138, label: 'R-k Kłokocin Pętla' },
            { value: 339, label: 'R-k Kłokocin Poligonowa' },
            { value: 140, label: 'R-k Kłokocin Urząd Celny' },
        ],
    },
    { label: 'Kotucza', options: [{ value: 364, label: 'Kotucza Cmentarz' }] },
    {
        label: 'Krzyżkowice',
        options: [{ value: 352, label: 'Krzyżkowice Skrzyżowanie' }],
    },
    {
        label: 'Książenice',
        options: [
            { value: 160, label: 'Książenice Brzozy' },
            { value: 161, label: 'Książenice Kościół' },
            { value: 341, label: 'Książenice Las' },
            { value: 340, label: 'Książenice Szkoła' },
        ],
    },
    {
        label: 'Kuźnia Raciborska',
        options: [
            { value: 235, label: 'Kuźnia Raciborska' },
            { value: 237, label: 'Kuźnia Raciborska DK' },
            { value: 236, label: 'Kuźnia Raciborska Kościół' },
            { value: 234, label: 'Kuźnia Raciborska Osiedle' },
            { value: 238, label: 'Kuźnia Raciborska Rafamet' },
        ],
    },
    {
        label: 'Leszczyny',
        options: [
            { value: 159, label: 'Leszczyny Broniewskiego' },
            { value: 158, label: 'Leszczyny Ligonia' },
            { value: 157, label: 'Leszczyny Rondo' },
        ],
    },
    { label: 'Ligota', options: [{ value: 248, label: 'Ligota Gimnazjum' }] },
    {
        label: 'Lyski',
        options: [
            { value: 190, label: 'Lyski Blazel' },
            { value: 411, label: 'Lyski Kamionki' },
            { value: 329, label: 'Lyski Las' },
            { value: 191, label: 'Lyski Rondo' },
            { value: 318, label: 'Lyski UPT' },
        ],
    },
    {
        label: 'Marklowice',
        options: [
            { value: 375, label: 'Marklowice Dolne' },
            { value: 376, label: 'Marklowice Słoneczna Wyspa' },
            { value: 79, label: 'Marklowice Wiosny Ludów Górka' },
            { value: 77, label: 'Marklowice Wiosny Ludów Kaplica' },
            { value: 78, label: 'Marklowice Wiosny Ludów Sklep' },
            { value: 330, label: 'Marklowice Wiosny LudówWidokowa' },
        ],
    },
    {
        label: 'Maroko-Nowiny',
        options: [
            { value: 338, label: 'Maroko Nowiny Ośrodek JPII' },
            { value: 337, label: 'Maroko Nowiny Piownik' },
            { value: 5, label: 'R-k Maroko Nowiny' },
            { value: 89, label: 'R-k Maroko Nowiny Brzozowa' },
            { value: 4, label: 'R-k Maroko Nowiny Chabrowa' },
            { value: 88, label: 'R-k Maroko Nowiny Graniczna' },
            { value: 434, label: 'R-k Maroko Nowiny Kominka' },
            { value: 379, label: 'R-k Maroko Nowiny Krakusa' },
            { value: 171, label: 'R-k Maroko Nowiny Księżok' },
            { value: 435, label: 'R-k Maroko Nowiny Orzepowicka' },
            { value: 46, label: 'R-k Maroko Nowiny Raciborska' },
            { value: 2, label: 'R-k Maroko Nowiny RondoMazamet' },
            { value: 24, label: 'R-k Maroko Nowiny Szkoła' },
            { value: 3, label: 'R-k Maroko NowinyBudowlanych' },
            { value: 6, label: 'R-k Maroko NowinyZebrzydowicka' },
        ],
    },
    {
        label: 'Meksyk',
        options: [
            { value: 256, label: 'Meksyk Prosta' },
            { value: 349, label: 'R-k Maroko NowinyŻołędziowa' },
            { value: 221, label: 'R-k Meksyk Budowlanka' },
            { value: 68, label: 'R-k Meksyk Kamyczek' },
            { value: 64, label: 'R-k Meksyk Park' },
            { value: 222, label: 'R-k Meksyk Tkoczów' },
        ],
    },
    {
        label: 'Mszana Wodzisławska',
        options: [
            { value: 381, label: 'Mszana Wodzisławska Boisko' },
            { value: 382, label: 'Mszana WodzisławskaSkrzyżowanie' },
        ],
    },
    { label: 'Nowa Wieś', options: [{ value: 319, label: 'Nowa Wieś' }] },
    {
        label: 'Obszary',
        options: [
            { value: 357, label: 'Obszary PKP' },
            { value: 75, label: 'Obszary Wiadukt' },
        ],
    },
    {
        label: 'Paruszowiec',
        options: [
            { value: 259, label: 'Paruszowiec Kościół' },
            { value: 249, label: 'Piaski Szkoła' },
            { value: 165, label: 'R-k Paruszowiec Piaski Błonia' },
            { value: 149, label: 'R-k Paruszowiec Piaski HutaSilesia' },
            { value: 150, label: 'R-k Paruszowiec Piaski Mikołowska' },
            { value: 166, label: 'R-k Paruszowiec Piaski Przemysłowa' },
            { value: 164, label: 'R-k Paruszowiec Piaski Stawowa' },
            { value: 167, label: 'R-k Paruszowiec Piaski Wolna' },
        ],
    },
    { label: 'Piece', options: [{ value: 193, label: 'Piece Gimnazjum' }] },
    {
        label: 'Śródmieście',
        options: [
            { value: 250, label: 'Plac Wolności' },
            { value: 40, label: 'R-k Śródmieście 3 Maja' },
            { value: 10, label: 'R-k Śródmieście Bazylika' },
            { value: 23, label: 'R-k Śródmieście Chrobrego' },
            { value: 261, label: 'R-k Śródmieście Dworek' },
            { value: 8, label: 'R-k Śródmieście DworzecKolejowy' },
            { value: 416, label: 'R-k Śródmieście Jankowicka' },
            { value: 91, label: 'R-k Śródmieście Jankowicka ZUS' },
            { value: 201, label: 'R-k Śródmieście Kampus' },
            { value: 9, label: 'R-k Śródmieście Kościuszki' },
            { value: 252, label: 'R-k Śródmieście Mikołowska Liceum' },
            { value: 63, label: 'R-k Śródmieście Piasta' },
            { value: 289, label: 'R-k Śródmieście Plac Wolności 1' },
            { value: 90, label: 'R-k Śródmieście Plac Wolności 2' },
            { value: 291, label: 'R-k Śródmieście Plac Wolności 3' },
            { value: 420, label: 'R-k Śródmieście Plac Wolności 3kon' },
            { value: 42, label: 'R-k Śródmieście Policja' },
            { value: 426, label: 'R-k Śródmieście Reymonta ZUS' },
            { value: 7, label: 'R-k Śródmieście Sąd' },
            { value: 41, label: 'R-k Śródmieście Urszulanki' },
            { value: 1, label: 'Rybnik DKM' },
            { value: 293, label: 'Rybnik Dworzec Autobusowy 2' },
            { value: 294, label: 'Rybnik Dworzec Autobusowy 3' },
            { value: 295, label: 'Rybnik Dworzec Autobusowy 4' },
            { value: 296, label: 'Rybnik Dworzec Autobusowy 5' },
            { value: 297, label: 'Rybnik Dworzec Autobusowy A' },
            { value: 347, label: 'Śródmieście Urząd Miasta' },
        ],
    },
    {
        label: 'Północ',
        options: [
            { value: 409, label: 'Północ  Strzelecka' },
            { value: 410, label: 'Północ  Żużlowa' },
            { value: 126, label: 'R-k Północ  Gliwicka Szpital' },
            { value: 262, label: 'R-k Północ  Janiego' },
            { value: 148, label: 'R-k Północ  Karolinka' },
            { value: 127, label: 'R-k Północ  Kąpielisko Ruda' },
            { value: 47, label: 'R-k Północ  Rondo Gliwickie' },
            { value: 106, label: 'R-k Północ  Rudzka Cmentarz' },
            { value: 418, label: 'R-k Północ  Strzelecka' },
            { value: 105, label: 'R-k Północ  Wawok' },
            { value: 258, label: 'R-k Północ  Wyzwolenia' },
            { value: 414, label: 'R-k Północ  Żużlowa' },
        ],
    },
    { label: 'Pstrężna', options: [{ value: 321, label: 'Pstrężna Centrum' }] },
    {
        label: 'Pszów',
        options: [
            { value: 353, label: 'Pszów Armii Krajowej Szkoła nr3' },
            { value: 356, label: 'Pszów Bazylika' },
            { value: 125, label: 'Pszów DA' },
            { value: 124, label: 'Pszów Traugutta ZSZ' },
            { value: 351, label: 'Pszów Wiadukt' },
        ],
    },
    {
        label: 'Radlin',
        options: [
            { value: 209, label: 'Radlin Domeyki' },
            { value: 62, label: 'Radlin Hallera Sokolnia' },
            { value: 60, label: 'Radlin Korfantego Centrum' },
            { value: 61, label: 'Radlin Korfantego KWK Marcel' },
            { value: 428, label: 'Radlin Korfantego Makuszyńskiego' },
            { value: 76, label: 'Radlin Marklowicka Dom Górnika' },
            { value: 424, label: 'Radlin Rogozina' },
            { value: 211, label: 'Radlin Rydułtowska Reden' },
            { value: 212, label: 'Radlin Rydułtowska RedenGórka' },
            { value: 210, label: 'Radlin Rymera Piekarnia' },
            { value: 377, label: 'Radlin Ujejskiego' },
            { value: 333, label: 'Radlin UM' },
        ],
    },
    {
        label: 'Radoszowy',
        options: [{ value: 86, label: 'Radoszowy Kościół' }],
    },
    {
        label: 'Raszczyce',
        options: [
            { value: 427, label: 'Raszczyce Centrum' },
            { value: 323, label: 'Raszczyce I' },
            { value: 324, label: 'Raszczyce Kościół' },
            { value: 425, label: 'Raszczyce Osrodek Zdrowia' },
        ],
    },
    {
        label: 'Boguszowice',
        options: [
            { value: 195, label: 'R-k Boguszowice Osiedle Jastrzębska' },
            { value: 20, label: 'R-k Boguszowice Osiedle Kopalnia' },
            { value: 21, label: 'R-k Boguszowice Osiedle Patriotów' },
            { value: 22, label: 'R-k Boguszowice Osiedle Pętla' },
            { value: 286, label: 'R-k Boguszowice Osiedle Rajska' },
            { value: 17, label: 'R-k Boguszowice Stare' },
            { value: 368, label: 'R-k Boguszowice Stare Błękitna' },
            { value: 141, label: 'R-k Boguszowice Stare Kłokocińska' },
            { value: 19, label: 'R-k Boguszowice Stare Małachowskiego' },
            { value: 18, label: 'R-k Boguszowice Stare Szkoła' },
            { value: 16, label: 'R-k Boguszowice StareRaszowiec' },
            { value: 288, label: 'R-k Boguszowice StareRejewskiego' },
            { value: 239, label: 'R-k Boguszowice StareSztolniowa' },
            { value: 240, label: 'R-k Boguszowice StareSztolniowa 1' },
        ],
    },
    {
        label: 'Golejów',
        options: [
            { value: 199, label: 'R-k Golejów Górka' },
            { value: 241, label: 'R-k Golejów Kaplica' },
            { value: 242, label: 'R-k Golejów Rondo' },
            { value: 216, label: 'R-k Golejów Siedliska' },
            { value: 200, label: 'R-k Golejów Skrzyżowanie' },
            { value: 213, label: 'R-k Golejów Szkoła' },
        ],
    },
    {
        label: 'Grabownia',
        options: [
            { value: 316, label: 'R-k Grabownia I' },
            { value: 215, label: 'R-k Grabownia Olszowiec' },
            { value: 214, label: 'R-k Grabownia Poloczka' },
            { value: 317, label: 'R-k Grabownia Sklep' },
        ],
    },
    {
        label: 'Ligota-Ligocka-Kuźnia',
        options: [
            { value: 372, label: 'R-k Ligocka Kuźnia Ligocka' },
            { value: 26, label: 'R-k Ligota Ligocka Kuźnia' },
            { value: 13, label: 'R-k Ligota Ligocka Kuźnia Kaplica' },
            { value: 169, label: 'R-k Ligota Ligocka Kuźnia Kościół' },
            { value: 14, label: 'R-k Ligota Ligocka Kuźnia RBoguszowicki' },
            { value: 168, label: 'R-k Ligota Ligocka Kuźnia Skrzyżowanie' },
            { value: 11, label: 'R-k Ligota Ligocka Kuźnia Wiadukt' },
            { value: 405, label: 'R-k Ligota Ligocka Kuźnia Wolna' },
            { value: 12, label: 'R-k Ligota Ligocka Kuźnia Żorska' },
            { value: 15, label: 'R-k Ligota Ligocka KuźniaBoguszowicka' },
        ],
    },
    {
        label: 'Niedobczyce',
        options: [
            { value: 56, label: 'R-k Niedobczyce Cegielnia' },
            { value: 401, label: 'R-k Niedobczyce Garbocze' },
            { value: 83, label: 'R-k Niedobczyce Hałdy' },
            { value: 82, label: 'R-k Niedobczyce Janasa' },
            { value: 71, label: 'R-k Niedobczyce Karolinka' },
            { value: 96, label: 'R-k Niedobczyce Kopalnia Rymer' },
            { value: 53, label: 'R-k Niedobczyce Niedobczycka' },
            { value: 73, label: 'R-k Niedobczyce Orlik' },
            { value: 70, label: 'R-k Niedobczyce Paryż' },
            { value: 72, label: 'R-k Niedobczyce Stadion' },
            { value: 54, label: 'R-k Niedobczyce Szkoła' },
            { value: 55, label: 'R-k Niedobczyce Wołodyjowskiego' },
            { value: 74, label: 'R-k Niedobczyce Wrębowa' },
        ],
    },
    {
        label: 'Niewiadom',
        options: [
            { value: 374, label: 'R-k Niewiadom Boisko' },
            { value: 205, label: 'R-k Niewiadom Buzowice' },
            { value: 58, label: 'R-k Niewiadom Dworzec Kol.' },
            { value: 85, label: 'R-k Niewiadom Frontowa' },
            { value: 87, label: 'R-k Niewiadom Kol Beata' },
            { value: 335, label: 'R-k Niewiadom Kol Helena' },
            { value: 59, label: 'R-k Niewiadom Kopalnia Ignacy' },
            { value: 304, label: 'R-k Niewiadom Morcinka' },
            { value: 57, label: 'R-k Niewiadom Racławicka' },
            { value: 404, label: 'R-k Niewiadom Sportowa' },
            { value: 84, label: 'R-k Niewiadom Szkoła' },
        ],
    },
    {
        label: 'Ochojec',
        options: [
            { value: 219, label: 'R-k Ochojec Centrum' },
            { value: 218, label: 'R-k Ochojec Kościół' },
            { value: 217, label: 'R-k Ochojec Młynek' },
        ],
    },
    {
        label: 'Orzepowice',
        options: [
            { value: 80, label: 'R-k Orzepowice Borki' },
            { value: 397, label: 'R-k Orzepowice Borki 1' },
            { value: 403, label: 'R-k Orzepowice Borki 2' },
            { value: 104, label: 'R-k Orzepowice Kuźnia' },
            { value: 107, label: 'R-k Orzepowice Rondo' },
            { value: 81, label: 'R-k Orzepowice Szpital Woj' },
        ],
    },
    {
        label: 'Popielów',
        options: [
            { value: 147, label: 'R-k Popielów Konarskiego' },
            { value: 99, label: 'R-k Popielów Kościół' },
            { value: 97, label: 'R-k Popielów Skrzyżowanie' },
            { value: 98, label: 'R-k Popielów Staffa' },
            { value: 229, label: 'R-k Popielów Wodzisławska' },
            { value: 402, label: 'R-k Popielów Worcella' },
            { value: 228, label: 'R-k Popielów Żabik' },
        ],
    },
    {
        label: 'Radziejów',
        options: [
            { value: 100, label: 'R-k Radziejów' },
            { value: 101, label: 'R-k Radziejów  Okulickiego' },
            { value: 102, label: 'R-k Radziejów  Świercze' },
        ],
    },
    {
        label: 'Rybnicka Kuźnia',
        options: [
            { value: 334, label: 'R-k Rybnicka Kuźnia Boisko' },
            { value: 134, label: 'R-k Rybnicka Kuźnia Chłodnie I' },
            { value: 350, label: 'R-k Rybnicka Kuźnia Chłodnie II' },
            { value: 133, label: 'R-k Rybnicka Kuźnia Elektrownia' },
            { value: 132, label: 'R-k Rybnicka Kuźnia Osiedle' },
            { value: 130, label: 'R-k Rybnicka Kuźnia Szkoła' },
            { value: 137, label: 'R-k Rybnicka Kuźnia WORD' },
            { value: 131, label: 'R-k Rybnicka KuźniaMaksymiliana' },
            { value: 247, label: 'Rybnicka Kuźnia Basen' },
            { value: 243, label: 'Rybnicka Kuźnia Gimnazjum  I' },
        ],
    },
    {
        label: 'Smolna',
        options: [
            { value: 48, label: 'R-k Smolna Franciszkanie' },
            { value: 43, label: 'R-k Smolna Kotucza' },
            { value: 25, label: 'R-k Smolna Krzyżowa' },
            { value: 49, label: 'R-k Smolna Osiedle' },
            { value: 45, label: 'R-k Smolna Reymonta' },
            { value: 344, label: 'R-k Smolna RondoWodzisławskie' },
            { value: 290, label: 'R-k Smolna Sławików' },
        ],
    },
    {
        label: 'Stodoły',
        options: [
            { value: 112, label: 'R-k Stodoły Kaplica' },
            { value: 111, label: 'R-k Stodoły Przystań' },
            { value: 406, label: 'R-k Stodoły Stadnina' },
        ],
    },
    {
        label: 'Wielopole',
        options: [
            { value: 129, label: 'R-k Wielopole Lipowa' },
            { value: 135, label: 'R-k Wielopole Skrzyżowanie' },
            { value: 136, label: 'R-k Wielopole Szkoła' },
            { value: 128, label: 'R-k Wielopole Wiadukt' },
        ],
    },
    {
        label: 'Zamysłów',
        options: [
            { value: 95, label: 'R-k Zamysłów Dolna' },
            { value: 94, label: 'R-k Zamysłów Dolna Las' },
            { value: 93, label: 'R-k Zamysłów Dolna Mostek' },
            { value: 203, label: 'R-k Zamysłów Gruntowa' },
            { value: 92, label: 'R-k Zamysłów Jankowicka' },
            { value: 51, label: 'R-k Zamysłów Niedobczycka' },
            { value: 50, label: 'R-k Zamysłów Plebiscytowa' },
            { value: 202, label: 'R-k Zamysłów Wodociągi' },
            { value: 69, label: 'R-k Zamysłów Wodzisławska' },
            { value: 52, label: 'R-k Zamysłów Wrzosy' },
        ],
    },
    {
        label: 'Zebrzydowice',
        options: [
            { value: 174, label: 'R-k Zebrzydowice' },
            { value: 399, label: 'R-k Zebrzydowice Kasztanowa' },
            { value: 400, label: 'R-k Zebrzydowice Las' },
            { value: 172, label: 'R-k Zebrzydowice Myto' },
            { value: 398, label: 'R-k Zebrzydowice Przedmieście' },
            { value: 173, label: 'R-k Zebrzydowice Szkoła' },
        ],
    },
    {
        label: 'Ruda Kozielska',
        options: [
            { value: 232, label: 'Ruda Kozielska' },
            { value: 233, label: 'Ruda Kozielska Las' },
            { value: 231, label: 'Ruda Kozielska Straż' },
        ],
    },
    {
        label: 'Rudy',
        options: [
            { value: 116, label: 'Rudy Kościół' },
            { value: 113, label: 'Rudy Paproć' },
            { value: 114, label: 'Rudy Rybnicka' },
            { value: 115, label: 'Rudy Skrzyżowanie' },
            { value: 348, label: 'Rudy Stacja Kolejki Wąskotorowej' },
        ],
    },
    {
        label: 'Rydułtowy',
        options: [
            { value: 187, label: 'Rydułtowy Bema Lidl' },
            { value: 185, label: 'Rydułtowy Bema Raciborska' },
            { value: 186, label: 'Rydułtowy Bema Stadion' },
            { value: 206, label: 'Rydułtowy Bohaterów W-wyCegielnia' },
            { value: 207, label: 'Rydułtowy Bohaterów W-wyOrlovska' },
            { value: 421, label: 'Rydułtowy Galeria' },
            { value: 220, label: 'Rydułtowy Kopalnia' },
            { value: 118, label: 'Rydułtowy Kowalski' },
            { value: 354, label: 'Rydułtowy KrzyżkowickaJesionowa' },
            { value: 355, label: 'Rydułtowy KrzyżkowickaOrzechowa' },
            { value: 120, label: 'Rydułtowy Mickiewicza' },
            { value: 422, label: 'Rydułtowy Obywatelska' },
            { value: 121, label: 'Rydułtowy Ofiar Terroru' },
            { value: 119, label: 'Rydułtowy Orłowiec' },
            { value: 423, label: 'Rydułtowy Ośrodek Zdrowia' },
            { value: 194, label: 'Rydułtowy Piecowska' },
            { value: 117, label: 'Rydułtowy Piekarnia' },
            { value: 208, label: 'Rydułtowy Plebiscytowa Szpital' },
            { value: 122, label: 'Rydułtowy Rynek' },
            { value: 123, label: 'Rydułtowy Traugutta Granica' },
        ],
    },
    {
        label: 'Sumina',
        options: [
            { value: 189, label: 'Sumina Centrum' },
            { value: 264, label: 'Sumina PKP' },
        ],
    },
    {
        label: 'Szczerbice',
        options: [
            { value: 178, label: 'Szczerbice' },
            { value: 276, label: 'Szczerbice Dwór' },
            { value: 313, label: 'Szczerbice Kaplica' },
            { value: 177, label: 'Szczerbice Piaskowa' },
            { value: 275, label: 'Szczerbice Radoszowska' },
            { value: 278, label: 'Szczerbice Straż' },
            { value: 277, label: 'Szczerbice Szkolna' },
        ],
    },
    {
        label: 'Szczygłowice',
        options: [
            { value: 342, label: 'Szczygłowice Al. Piastów' },
            { value: 343, label: 'Szczygłowice Kopalnia' },
        ],
    },
    {
        label: '',
        options: [
            { value: 244, label: 'Sztolniowa Gimnazjum' },
            { value: 253, label: 'Za Komendą' },
        ],
    },
    {
        label: 'Świerklany',
        options: [
            { value: 309, label: 'Świerklany Bar Karliczek' },
            { value: 306, label: 'Świerklany Dolne' },
            { value: 299, label: 'Świerklany Górne' },
            { value: 388, label: 'Świerklany Górne Szkoła' },
            { value: 305, label: 'Świerklany Ośrodek Zdrowia' },
            { value: 300, label: 'Świerklany Piekarnia' },
            { value: 298, label: 'Świerklany Plebiscytowa' },
            { value: 308, label: 'Świerklany Szkoła Gimnazjum' },
            { value: 310, label: 'Świerklany Szyb' },
        ],
    },
    {
        label: 'Wodzisław',
        options: [
            { value: 380, label: 'Wodzisław Cyganek' },
            { value: 363, label: 'Wodzisław Dw. Aut' },
            { value: 362, label: 'Wodzisław Dworzec PKP' },
        ],
    },
    {
        label: 'Zwonowice',
        options: [
            { value: 144, label: 'Zwonowice Classen' },
            { value: 146, label: 'Zwonowice Szkoła' },
            { value: 145, label: 'Zwonowice Wyzwolenia' },
        ],
    },
    {
        label: 'Żory',
        options: [
            { value: 36, label: 'Żory Al. Jana Pawła II Sąd' },
            { value: 37, label: 'Żory Al. Jana Pawła IIBajerówka' },
            { value: 35, label: 'Żory Al. Niepodległości' },
            { value: 39, label: 'Żory Biskupa' },
            { value: 34, label: 'Żory Dworzec Autobusowy' },
            { value: 32, label: 'Żory Rybnicka Cmentarz' },
            { value: 378, label: 'Żory Rybnicka Granica' },
            { value: 33, label: 'Żory Rybnicka Kłapczyka' },
            { value: 30, label: 'Żory Rybnicka Pałki' },
            { value: 373, label: 'Żory Rybnicka Rondo' },
            { value: 31, label: 'Żory Rybnicka Strefa' },
            { value: 331, label: 'Żory Rybnicka Świetlica' },
            { value: 29, label: 'Żory Rybnicka Wiśniowa' },
            { value: 38, label: 'Żory Stodolna Cmentarz' },
        ],
    },
    {
        label: 'Żuków',
        options: [
            { value: 182, label: 'Żuków' },
            { value: 181, label: 'Żuków PKP' },
        ],
    },
    { label: 'Żytna', options: [{ value: 322, label: 'Żytna Centrum' }] },
];
